keys:
  # Your workstation age key - generate with: age-keygen -o ~/.config/sops/age/keys.txt
  - &user_key age1q0e7q4cyh9vmqfdgnnpty7dnfvjaf65xud2xdhqlr982qxxfly0q680rp6
  # Server's age key (Beelink ME Pro homeserver)
  - &host_homeserver age1dytr8nzy7kc50qpnrt4x9sl9eulwygrdnunnq02wrn2dgtazsfnsmrq48j

creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - age:
          - *user_key
          - *host_homeserver
