#!/usr/bin/env bash
# NixOS Home Server - Setup Script
# This script collects user-specific configuration and generates user-config.nix

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/user-config.nix"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color
BOLD='\033[1m'

print_header() {
    echo ""
    echo -e "${BLUE}╔════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║${NC}     ${BOLD}NixOS Home Server - Configuration Setup${NC}                    ${BLUE}║${NC}"
    echo -e "${BLUE}╚════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
}

print_section() {
    echo ""
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${CYAN}  $1${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
}

prompt() {
    local var_name="$1"
    local prompt_text="$2"
    local default="${3:-}"
    local value

    if [[ -n "$default" ]]; then
        echo -e -n "${GREEN}?${NC} ${prompt_text} ${YELLOW}[$default]${NC}: "
        read -r value
        value="${value:-$default}"
    else
        echo -e -n "${GREEN}?${NC} ${prompt_text}: "
        read -r value
    fi

    eval "$var_name=\"\$value\""
}

prompt_required() {
    local var_name="$1"
    local prompt_text="$2"
    local value=""

    while [[ -z "$value" ]]; do
        echo -e -n "${GREEN}?${NC} ${prompt_text} ${RED}(required)${NC}: "
        read -r value
        if [[ -z "$value" ]]; then
            echo -e "${RED}  This field is required. Please enter a value.${NC}"
        fi
    done

    eval "$var_name=\"\$value\""
}

prompt_choice() {
    local var_name="$1"
    local prompt_text="$2"
    shift 2
    local options=("$@")

    echo -e "${GREEN}?${NC} ${prompt_text}"
    local i=1
    for opt in "${options[@]}"; do
        echo -e "   ${YELLOW}$i)${NC} $opt"
        ((i++))
    done

    local choice
    while true; do
        echo -e -n "   Enter choice [1-${#options[@]}]: "
        read -r choice
        if [[ "$choice" =~ ^[0-9]+$ ]] && ((choice >= 1 && choice <= ${#options[@]})); then
            eval "$var_name=\"\${options[$((choice-1))]}\""
            break
        else
            echo -e "${RED}   Invalid choice. Please enter a number between 1 and ${#options[@]}.${NC}"
        fi
    done
}

detect_network_interface() {
    # Try to detect the primary network interface
    local interface
    interface=$(ip route get 8.8.8.8 2>/dev/null | grep -oP 'dev \K\S+' | head -1 || echo "")
    if [[ -z "$interface" ]]; then
        # Fallback: list available interfaces
        interface=$(ip link show | grep -E '^[0-9]+: (en|eth)' | head -1 | cut -d: -f2 | tr -d ' ' || echo "enp3s0")
    fi
    echo "$interface"
}

detect_disk_device() {
    # List available block devices
    echo -e "${YELLOW}Available disks:${NC}"
    lsblk -d -o NAME,SIZE,TYPE,MODEL 2>/dev/null | grep -E '^(nvme|sd|vd)' || echo "  (could not detect disks)"
    echo ""
}

generate_config() {
    cat > "$CONFIG_FILE" << EOF
# User Configuration
# Generated by setup.sh on $(date)
# Re-run setup.sh to regenerate this file with new values.

{
  # ============================================================================
  # SYSTEM IDENTITY
  # ============================================================================
  hostname = "${HOSTNAME}";
  domain = "${DOMAIN}";

  # ============================================================================
  # USER ACCOUNT
  # ============================================================================
  username = "${USERNAME}";
  userDescription = "${USER_DESCRIPTION}";
  sshPublicKey = "${SSH_PUBLIC_KEY}";

  # ============================================================================
  # LOCALE & TIMEZONE
  # ============================================================================
  timeZone = "${TIMEZONE}";
  locale = "${LOCALE}";
  keyMap = "${KEYMAP}";
  phoneRegion = "${PHONE_REGION}";

  # ============================================================================
  # NETWORK CONFIGURATION
  # ============================================================================
  networkInterface = "${NETWORK_INTERFACE}";
  ipAddress = "${IP_ADDRESS}";
  prefixLength = ${PREFIX_LENGTH};
  gateway = "${GATEWAY}";

  # ============================================================================
  # HARDWARE
  # ============================================================================
  diskDevice = "${DISK_DEVICE}";
  cpuVendor = "${CPU_VENDOR}";
  platform = "${PLATFORM}";

  # ============================================================================
  # SECRETS & KEYS
  # ============================================================================
  # These will be filled in after initial deployment when host keys are generated
  userAgeKey = "${USER_AGE_KEY}";
  hostAgeKey = "${HOST_AGE_KEY}";

  # ============================================================================
  # AUTO-UPGRADE (optional)
  # ============================================================================
  githubUsername = "${GITHUB_USERNAME}";
  githubRepo = "${GITHUB_REPO}";
}
EOF
}

generate_sops_yaml() {
    cat > "${SCRIPT_DIR}/.sops.yaml" << EOF
keys:
  # Your workstation age key - generate with: age-keygen -o ~/.config/sops/age/keys.txt
  - &user_key ${USER_AGE_KEY}
  # Server's SSH host key - derived via ssh-to-age after first boot
  - &host_${HOSTNAME} ${HOST_AGE_KEY}

creation_rules:
  - path_regex: secrets/secrets\\.yaml\$
    key_groups:
      - age:
          - *user_key
          - *host_${HOSTNAME}
EOF
}

create_secrets_template() {
    if [[ ! -f "${SCRIPT_DIR}/secrets/secrets.yaml" ]]; then
        cat > "${SCRIPT_DIR}/secrets/secrets.yaml.template" << EOF
# Secrets Template
# Copy this to secrets.yaml and fill in your actual secrets
# Then encrypt with: sops -e -i secrets/secrets.yaml

# Admin user password hash (generate with: mkpasswd -m sha-512)
admin:
    password_hash: "YOUR_PASSWORD_HASH_HERE"

# Nextcloud admin password (if using Nextcloud module)
nextcloud:
    admin_password: "YOUR_NEXTCLOUD_ADMIN_PASSWORD"

# Authentik secrets (if using Authentik module)
authentik:
    db_password: "YOUR_AUTHENTIK_DB_PASSWORD"
    secret_key: "YOUR_AUTHENTIK_SECRET_KEY"

# WireGuard private key (if using WireGuard module)
# Generate with: wg genkey
wireguard:
    private_key: "YOUR_WIREGUARD_PRIVATE_KEY"
EOF
        echo -e "${GREEN}Created secrets template at: secrets/secrets.yaml.template${NC}"
    fi
}

# ============================================================================
# MAIN SCRIPT
# ============================================================================

print_header

echo -e "This script will help you configure your NixOS home server."
echo -e "Press ${CYAN}Enter${NC} to accept default values shown in ${YELLOW}[brackets]${NC}."
echo ""

# Check for existing config
if [[ -f "$CONFIG_FILE" ]] && ! grep -q "PLACEHOLDER" "$CONFIG_FILE"; then
    echo -e "${YELLOW}An existing configuration was found.${NC}"
    prompt OVERWRITE "Do you want to overwrite it?" "no"
    if [[ "${OVERWRITE,,}" != "yes" && "${OVERWRITE,,}" != "y" ]]; then
        echo -e "${BLUE}Exiting without changes.${NC}"
        exit 0
    fi
fi

# ============================================================================
# SYSTEM IDENTITY
# ============================================================================
print_section "System Identity"

prompt HOSTNAME "Hostname for your server" "homeserver"
prompt DOMAIN "Local domain suffix" "home"

# ============================================================================
# USER ACCOUNT
# ============================================================================
print_section "User Account"

prompt USERNAME "Admin username" "admin"
prompt USER_DESCRIPTION "User description" "Home server administrator"

echo -e "\n${YELLOW}Your SSH public key is required for secure access.${NC}"
echo -e "You can find it at: ~/.ssh/id_ed25519.pub or ~/.ssh/id_rsa.pub"
echo ""

# Try to auto-detect SSH key
DEFAULT_SSH_KEY=""
for keyfile in ~/.ssh/id_ed25519.pub ~/.ssh/id_rsa.pub ~/.ssh/id_ecdsa.pub; do
    if [[ -f "$keyfile" ]]; then
        DEFAULT_SSH_KEY=$(cat "$keyfile")
        echo -e "${GREEN}Found SSH key: $keyfile${NC}"
        break
    fi
done

if [[ -n "$DEFAULT_SSH_KEY" ]]; then
    prompt SSH_PUBLIC_KEY "SSH public key" "$DEFAULT_SSH_KEY"
else
    prompt_required SSH_PUBLIC_KEY "SSH public key (paste the entire line)"
fi

# ============================================================================
# LOCALE & TIMEZONE
# ============================================================================
print_section "Locale & Timezone"

# Detect current timezone
CURRENT_TZ=$(timedatectl show --property=Timezone --value 2>/dev/null || echo "Europe/London")

prompt TIMEZONE "Timezone" "$CURRENT_TZ"
prompt LOCALE "System locale" "en_GB.UTF-8"
prompt KEYMAP "Console keymap" "uk"
prompt PHONE_REGION "Phone region code (ISO 3166-1 alpha-2)" "GB"

# ============================================================================
# NETWORK CONFIGURATION
# ============================================================================
print_section "Network Configuration"

echo -e "${YELLOW}Setting up static IP configuration for your server.${NC}"
echo ""

# Detect network interface
DETECTED_IFACE=$(detect_network_interface)
prompt NETWORK_INTERFACE "Network interface" "$DETECTED_IFACE"

# Try to detect current IP
CURRENT_IP=$(ip addr show "$NETWORK_INTERFACE" 2>/dev/null | grep 'inet ' | awk '{print $2}' | cut -d/ -f1 | head -1 || echo "192.168.1.100")
CURRENT_PREFIX=$(ip addr show "$NETWORK_INTERFACE" 2>/dev/null | grep 'inet ' | awk '{print $2}' | cut -d/ -f2 | head -1 || echo "24")
CURRENT_GW=$(ip route | grep default | awk '{print $3}' | head -1 || echo "192.168.1.1")

prompt IP_ADDRESS "Static IP address" "$CURRENT_IP"
prompt PREFIX_LENGTH "Network prefix length (CIDR)" "$CURRENT_PREFIX"
prompt GATEWAY "Default gateway" "$CURRENT_GW"

# ============================================================================
# HARDWARE
# ============================================================================
print_section "Hardware Configuration"

detect_disk_device
prompt DISK_DEVICE "Target disk device" "/dev/nvme0n1"

echo ""
prompt_choice CPU_VENDOR "CPU vendor" "intel" "amd"

prompt_choice PLATFORM "System architecture" "x86_64-linux" "aarch64-linux"

# ============================================================================
# SECRETS & KEYS
# ============================================================================
print_section "Encryption Keys"

echo -e "${YELLOW}SOPS/Age keys are used to encrypt secrets.${NC}"
echo ""

# Check for existing age key
AGE_KEY_FILE="$HOME/.config/sops/age/keys.txt"
if [[ -f "$AGE_KEY_FILE" ]]; then
    DETECTED_AGE_KEY=$(grep 'public key:' "$AGE_KEY_FILE" 2>/dev/null | awk '{print $4}' || echo "")
    if [[ -z "$DETECTED_AGE_KEY" ]]; then
        DETECTED_AGE_KEY=$(age-keygen -y "$AGE_KEY_FILE" 2>/dev/null || echo "")
    fi
    if [[ -n "$DETECTED_AGE_KEY" ]]; then
        echo -e "${GREEN}Found age key at: $AGE_KEY_FILE${NC}"
    fi
fi

if [[ -n "${DETECTED_AGE_KEY:-}" ]]; then
    prompt USER_AGE_KEY "Your workstation age public key" "$DETECTED_AGE_KEY"
else
    echo -e "Generate one with: ${CYAN}age-keygen -o ~/.config/sops/age/keys.txt${NC}"
    prompt USER_AGE_KEY "Your workstation age public key" "age1..."
fi

echo ""
echo -e "${YELLOW}The host age key is derived from the server's SSH host key.${NC}"
echo -e "This will be generated after the first deployment."
echo -e "You can derive it later with: ${CYAN}ssh-keyscan <server-ip> | ssh-to-age${NC}"
prompt HOST_AGE_KEY "Server host age key (or leave as placeholder)" "age1..."

# ============================================================================
# AUTO-UPGRADE
# ============================================================================
print_section "Auto-Upgrade (Optional)"

echo -e "${YELLOW}If you host your config on GitHub, auto-upgrade can pull updates automatically.${NC}"
echo ""

prompt GITHUB_USERNAME "GitHub username (or leave empty to skip)" ""
if [[ -n "$GITHUB_USERNAME" ]]; then
    prompt GITHUB_REPO "GitHub repository name" "nixos-config"
else
    GITHUB_REPO=""
fi

# ============================================================================
# GENERATE CONFIGURATION
# ============================================================================
print_section "Generating Configuration"

generate_config
echo -e "${GREEN}Generated: user-config.nix${NC}"

generate_sops_yaml
echo -e "${GREEN}Generated: .sops.yaml${NC}"

create_secrets_template

# ============================================================================
# NEXT STEPS
# ============================================================================
print_section "Next Steps"

echo -e "Your configuration has been generated. Here's what to do next:"
echo ""
echo -e "  ${CYAN}1.${NC} Review the generated ${YELLOW}user-config.nix${NC}"
echo ""
echo -e "  ${CYAN}2.${NC} Create your secrets file:"
echo -e "     ${YELLOW}cp secrets/secrets.yaml.template secrets/secrets.yaml${NC}"
echo -e "     Edit with your actual passwords and keys"
echo -e "     ${YELLOW}sops -e -i secrets/secrets.yaml${NC}"
echo ""
echo -e "  ${CYAN}3.${NC} Generate password hash for your admin user:"
echo -e "     ${YELLOW}mkpasswd -m sha-512${NC}"
echo ""
echo -e "  ${CYAN}4.${NC} Deploy to your target machine:"
echo -e "     ${YELLOW}nix run github:nix-community/nixos-anywhere -- \\${NC}"
echo -e "     ${YELLOW}  --flake .#homeserver root@<target-ip>${NC}"
echo ""
echo -e "  ${CYAN}5.${NC} After first boot, get the server's age key:"
echo -e "     ${YELLOW}ssh-keyscan <server-ip> 2>/dev/null | ssh-to-age${NC}"
echo -e "     Update ${YELLOW}user-config.nix${NC} and ${YELLOW}.sops.yaml${NC} with this key"
echo -e "     Re-encrypt secrets: ${YELLOW}sops updatekeys secrets/secrets.yaml${NC}"
echo ""
echo -e "${GREEN}Setup complete!${NC}"
echo ""
