# User Configuration
# This file is generated by setup.sh - DO NOT edit manually unless you know what you're doing.
# Re-run setup.sh to regenerate this file with new values.

{
  # ============================================================================
  # SYSTEM IDENTITY
  # ============================================================================
  hostname = "PLACEHOLDER_HOSTNAME";
  domain = "PLACEHOLDER_DOMAIN";

  # ============================================================================
  # USER ACCOUNT
  # ============================================================================
  username = "PLACEHOLDER_USERNAME";
  userDescription = "PLACEHOLDER_USER_DESCRIPTION";
  sshPublicKey = "PLACEHOLDER_SSH_PUBLIC_KEY";

  # ============================================================================
  # LOCALE & TIMEZONE
  # ============================================================================
  timeZone = "PLACEHOLDER_TIMEZONE";
  locale = "PLACEHOLDER_LOCALE";
  keyMap = "PLACEHOLDER_KEYMAP";
  phoneRegion = "PLACEHOLDER_PHONE_REGION";

  # ============================================================================
  # NETWORK CONFIGURATION
  # ============================================================================
  networkInterface = "PLACEHOLDER_NETWORK_INTERFACE";
  ipAddress = "PLACEHOLDER_IP_ADDRESS";
  prefixLength = 24;  # PLACEHOLDER - update via setup.sh
  gateway = "PLACEHOLDER_GATEWAY";

  # ============================================================================
  # HARDWARE
  # ============================================================================
  diskDevice = "PLACEHOLDER_DISK_DEVICE";
  cpuVendor = "PLACEHOLDER_CPU_VENDOR";  # "intel" or "amd"
  platform = "PLACEHOLDER_PLATFORM";      # "x86_64-linux" or "aarch64-linux"

  # ============================================================================
  # SECRETS & KEYS
  # ============================================================================
  userAgeKey = "PLACEHOLDER_USER_AGE_KEY";
  hostAgeKey = "PLACEHOLDER_HOST_AGE_KEY";

  # ============================================================================
  # AUTO-UPGRADE (optional)
  # ============================================================================
  githubUsername = "PLACEHOLDER_GITHUB_USERNAME";
  githubRepo = "PLACEHOLDER_GITHUB_REPO";
}
